---
title: "A Fairwell to Fairless"
date: "03/07/2020"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
source('chris_card.R')
loc <- "../data/processed/"
```

![`r image_names[x]`](`r paste0("../data/",image_files[x])`)

```{r}
htmltools::includeHTML(paste0(loc,"messages_",x,".html"))
x <- x+1
```

![`r image_names[x]`](`r paste0("../data/",image_files[x])`)

```{r}
htmltools::includeHTML(paste0(loc,"messages_",x,".html"))
x <- x+1
```

![`r image_names[x]`](`r paste0("../data/",image_files[x])`)

```{r}
htmltools::includeHTML(paste0(loc,"messages_",x,".html"))
x <- x+1
```

![`r image_names[x]`](`r paste0("../data/",image_files[x])`)

```{r}
htmltools::includeHTML(paste0(loc,"messages_",x,".html"))
x <- x+1
```

![`r image_names[x]`](`r paste0("../data/",image_files[x])`)

```{r}
htmltools::includeHTML(paste0(loc,"messages_",x,".html"))
x <- x+1
```

![`r image_names[x]`](`r paste0("../data/",image_files[x])`)

```{r}
htmltools::includeHTML(paste0(loc,"messages_",x,".html"))
x <- x+1
```

![`r image_names[x]`](`r paste0("../data/",image_files[x])`)

